services:
  nginx:
      image: nginx:alpine
      restart: always
      ports:
        - "80:80"
      volumes:
        - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
        
  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD_FILE: /run/secrets/mysql_password
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
    secrets:
      - mysql_password
      - mysql_root_password
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -uroot -p$$(cat /run/secrets/mysql_root_password)"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}

    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    ports:
      - "15672:15672"
    healthcheck:
      test: ["CMD-SHELL", "rabbitmq-diagnostics -q ping"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  redis:
    image: redis:7-alpine
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  migrate:
    build: .
    env_file: .env
    environment:
      FLASK_APP: run:flask_app
    secrets:
      - mysql_password
      - secret_key
      - app_verification_secret
    command: wait-for-it mysql:3306 -t 90 -- flask db upgrade
    depends_on:
      mysql:
        condition: service_healthy
  web:
    build: .
    env_file: .env
    environment:
      FLASK_APP: run:flask_app
    secrets:
      - mysql_password
      - secret_key
      - app_verification_secret
    depends_on:
      mysql:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully

  celery_worker:
    build: .
    command: celery -A app.celery_app.celery worker --loglevel=info
    env_file: .env
    environment:
      FLASK_APP: run:flask_app
    secrets:
      - mysql_password
      - secret_key
      - app_verification_secret
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy

volumes:
  mysql_data:
  rabbitmq_data:
  redis_data:

secrets:
  mysql_password:
    file: ./secrets/mysql_password
  mysql_root_password:
    file: ./secrets/mysql_root_password
  secret_key:
    file: ./secrets/secret_key
  app_verification_secret:
    file: ./secrets/app_verification_secret
