services:
  web:
    command: flask --app run:flask_app run --host=0.0.0.0 --debug
    volumes:
      - .:/app
    environment:
      FLASK_APP: run:flask_app
      FLASK_DEBUG: 1
  
  celery_worker:
    volumes:
      - .:/app